from django.urls import path
from .views import login_view
from . import views

urlpatterns = [
    path('', login_view, name='login'),
    path('registro/', views.registro_view, name='registro'),
    path('clave_olvidada/', views.clave_olvidada, name='Clave_Olvidada'),
    path('clave_cambiada/', views.clave_cambiada, name='clave_cambiada'),
    path('admin/', views.vista_adm, name='vista_adm'),
    path('usuarios/', views.usuarios_view, name='usuarios'),
    path('clientes/', views.clientes_view, name='clientes'),
    path('clientes/', views.lista_clientes, name='clientes'),
    path('clientes/registrar/', views.registrar_cliente_view, name='registrar_cliente'),
    path('usuarios/registrar/', views.registrar_usuario_view, name='registrar_usuario'),
    path('home-Vista_cliente/', views.home_cliente, name='home_cliente'),
    path('ubicacion/', views.ubicacion, name='ubicacion'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('perfil/', views.mi_perfil, name='mi_perfil'),
    path('cajero/', views.vista_cajero, name='vista_cajero'),
    path('mesero/', views.vista_mesero, name='vista_mesero'),
    path('repartidor/', views.vista_repartidor, name='vista_repartidor'),
    path('perfil/cajero/', views.perfil_cajero, name='perfil_cajero'),
    path('perfil/mesero/', views.perfil_mesero, name='perfil_mesero'),
    path('perfil/repartidor/', views.perfil_repartidor, name='perfil_repartidor'),
    path('clientes/actualizar/<int:id>/', views.actualizar_cliente, name='actualizar_cliente'),
    path('clientes/eliminar/<int:id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('productos/', views.productos, name='productos'),
    path('productos/registrar/', views.registrar_producto, name='registrar_producto'),
    path('productos/eliminar/<int:id>/', views.eliminar_producto, name='eliminar_producto'),
    path('productos/actualizar/<int:id>/', views.actualizar_producto, name='actualizar_producto'),
    path('productos/eliminar/<int:id>/', views.eliminar_producto, name='eliminar_producto'),
    path('productos/aplicar-descuento/', views.aplicar_descuento, name='aplicar_descuento'),
    path('productos/quitar-descuento/', views.quitar_descuento, name='quitar_descuento'),

    path('mesas/', views.mesas_view, name='mesas'),
    path('mesas/registrar/', views.registrar_mesa_view, name='registrar_mesa'),
    path('mesa/actualizar/<int:id>/', views.actualizar_mesa, name='actualizar_mesa'),
    path('mesa/eliminar/<int:id>/', views.eliminar_mesa, name='eliminar_mesa'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('pedidos/registrar/', views.registrar_pedido, name='registrar_pedido'),
    path('pedidos/actualizar/<int:id>/', views.actualizar_pedido, name='actualizar_pedido'),
    path('pedidos/eliminar/<int:id>/', views.eliminar_pedido, name='eliminar_pedido'),
    path('pedidos/<int:id>/detalles/', views.ver_detalle_pedido, name='ver_detalle_pedido'),
    path('pedidos/<int:id>/detalles/agregar/', views.agregar_detalle_pedido, name='agregar_detalle_pedido'),
    path('pedidos/<int:id>/detalles/guardar/', views.guardar_detalles_pedido, name='guardar_detalles_pedido'),
    path('pedidos/<int:pedido_id>/pdf/', views.generar_pdf, name='pdf_pedido'),
    path('pedidos/<int:pedido_id>/detalles/modificar/', views.modificar_detalle_pedido, name='modificar_detalle_pedido'),
    path('pedido/guardar-ajax/', views.guardar_carrito_ajax, name='guardar_carrito_ajax'),
    # Módulo pedidos
    path('panel/pedidos/', views.pedidos_list, name='pedidos_list'),
    path('panel/pedidos/nuevo/', views.pedidos_create, name='pedidos_create'),
    path('panel/pedidos/ver/<int:id>/', views.pedidos_detail, name='pedidos_detail'),
    path('panel/pedidos/editar/<int:id>/', views.pedidos_edit, name='pedidos_edit'),
    path('panel/pedidos/eliminar/<int:id>/', views.pedidos_delete, name='pedidos_delete'),
    path('panel/pedidos/cambiar-estado/<int:id>/', views.pedidos_cambiar_estado, name='pedidos_cambiar_estado'),
    # Módulo pagos
    path('pagos/', views.pagos_list, name='pagos_list'),
    path('pedidos/<int:pedido_id>/pagar/', views.registrar_pago, name='registrar_pago'),
    path('pagos/<int:pago_id>/editar/', views.editar_pago, name='editar_pago'),
    path('pagos/<int:pago_id>/eliminar/', views.eliminar_pago, name='eliminar_pago'),
    path('pagos/imprimir/<int:pago_id>/', views.imprimir_factura, name='imprimir_factura'),
    # Módulo pagos - cliente
    path('home-Vista_cliente/pago', views.vistaPagos, name='pagos'),
    path('home-Vista_cliente/pago/<int:pedido_id>/', views.vistaPagos, name='pagos'),
    # endpoint de la confirmacion del pago
    path("pago/confirmar/<int:pedido_id>/", views.confirmar_pago, name="confirmar_pago"),

    path("admin/inventario/", views.vista_inventario, name="vista_inventario"),

]
