# Generated by Django 5.2.7 on 2025-10-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255, unique=True)),
                ('respuesta', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pregunta Clave',
                'verbose_name_plural': 'Preguntas Clave',
                'db_table': 'pregunta_clave',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregunta_clave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.preguntaclave'),
        ),
    ]
