# Generated by Django 5.2.7 on 2025-10-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_preguntaclave_usuario_rol_usuario_pregunta_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Login',
            name='pregunta_clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='Login',
            name='respuesta_clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PreguntaClave',
        ),
    ]
