# Generated by Django 5.2.7 on 2025-10-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
