# Generated by Django 5.2.7 on 2025-10-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',   # ✅ CORREGIDO
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]

