# Generated by Django 5.2.7 on 2026-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_categoria_mesa_pedido_pago_producto_detallepedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en porcentaje (ej: 10.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA en porcentaje (ej: 15.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
