# Generated by Django 5.2.7 on 2026-01-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_alter_categoria_options_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('pacifico', 'Banco del Pacífico'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('internacional', 'Banco Internacional'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_otro',
            field=models.CharField(blank=True, help_text="Especifique el banco si selecciona 'Otro'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='codigo_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_pagador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
