# Generated by Django 5.2.7 on 2026-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_pago_banco_pago_banco_otro_pago_codigo_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='completado', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
